### ISSUE TITLE
How to update bulbs color?

### ISSUE THREAD

**Issue by huongta157** [tuya/tuya-home-android-sdk-sample-kotlin#15]
**Describe the bug**
I follow these docs https://developer.tuya.com/en/docs/app-development/andoird_device_control?id=Kaixh4pfm8f0y to change the color of the bulbs. But it not working.
Please help me, thanks.

**Comment by radishwu** [comment]
@huongta157 We are very sorry, we suggest you move here to ask your question: https://service.console.tuya.com/8/3/create?step=4&id=01030408&source=suspension,to provide you with one-on-one guidance to match.
