### ISSUE TITLE
一直权限校验失败咋解决

### ISSUE THREAD

**Issue by linxiangcheer** [tuya/tuya-home-android-sdk-sample-kotlin#2]

**Comment by TONGHUI97** [comment]
检查一下是否按介入文档修改了配置，主要有以下四点：安全图片，注意名字，位置； app key ，app secret， app，id，这三个是否对应。

**Comment by TONGHUI97** [comment]
相关指导链接：https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj
