### ISSUE TITLE
thingMapping.gradle

### ISSUE THREAD

**Issue by zheng351138312** [tuya/tuya-home-android-sdk-sample-kotlin#29]
**Describe the bug**

**To Reproduce**

> Could not read script 'D:\Products\duya-home-demo\homesdk_sample\app\thingMapping.gradle' as it does not exist.

**Comment by MRwangqi** [comment]
@zheng351138312 

https://github.com/tuya/tuya-home-android-sdk-sample-java/blob/main/homesdk-sample/app/thingMapping.gradle

**Comment by zheng351138312** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
