### ISSUE TITLE
Could not find cn.yipianfengye.android:zxing-library:2.2

### ISSUE THREAD

**Issue by michael19900101** [tuya/tuya-home-android-sdk-sample-kotlin#43]
Could not find cn.yipianfengye.android:zxing-library:2.2

**Comment by MRwangqi** [comment]
@michael19900101 

Add the following maven source     

maven { url 'https://maven.aliyun.com/nexus/content/repositories/central/' }
maven { url 'https://maven.aliyun.com/repository/public' }

**Comment by michael19900101** [comment]
ok

**Comment by michael19900101** [comment]
ok
